In [1]:
import pandas as pd
data = pd.read_csv('C:/Users/Pranav/Downloads/churn-modelling/Churn_Modelling.csv')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [2]:
data.drop(['CustomerId', 'RowNumber','Surname'], axis=1, inplace = True)

In [3]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [4]:
data.Gender = [1 if each == 'Female' else 0 for each in data.Gender]
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       1   42       2       0.00              1   
1          608     Spain       1   41       1   83807.86              1   
2          502    France       1   42       8  159660.80              3   
3          699    France       1   39       1       0.00              2   
4          850     Spain       1   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [5]:
data = pd.get_dummies(prefix = "Geo", data = data, columns = ['Geography'])
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geo_France  Geo_Germany  Geo_Spain  
0               1        101348.88       1           1            0          0  
1               1        112542.58       0           0            0          1  
2               0        113931.57       1           1            0          0  
3               0         93826.63       0           1            0          0  
4               1         79084.10       0           0            0          1

In [7]:
y = data.Exited.values
print(y)

[1 0 1 ... 1 1 0]


In [8]:
x = data.drop(['Exited'], axis = 1)
x.describe()
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       1   42       2       0.00              1          1   
1          608       1   41       1   83807.86              1          0   
2          502       1   42       8  159660.80              3          1   
3          699       1   39       1       0.00              2          0   
4          850       1   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geo_France  Geo_Germany  Geo_Spain  
0               1        101348.88           1            0          0  
1               1        112542.58           0            0          1  
2               0        113931.57           1            0          0  
3               0         93826.63           1            0          0  
4               1         79084.10           0            0          1

In [9]:
import numpy as np
x_norm = (x- np.min(x)) / (np.max(x) - np.min(x))
x_norm.describe()

CreditScore        Gender           Age        Tenure       Balance  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       0.601058      0.454300      0.282727      0.501280      0.304848   
std        0.193307      0.497932      0.141727      0.289217      0.248696   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.468000      0.000000      0.189189      0.300000      0.000000   
50%        0.604000      0.000000      0.256757      0.500000      0.387402   
75%        0.736000      1.000000      0.351351      0.700000      0.508749   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

       NumOfProducts    HasCrCard  IsActiveMember  EstimatedSalary  \
count   10000.000000  10000.00000    10000.000000     10000.000000   
mean        0.176733      0.70550        0.515100         0.500441   
std         0.193885      0.45584        0.499797         0.287580   
min         0.000000      0.00000        0.000000         0.000000   
25%         0.000000      0.00000        0.000000         0.254977   
50%         0.000000      1.00000        1.000000         0.500960   
75%         0.333333      1.00000        1.000000         0.746955   
max         1.000000      1.00000        1.000000         1.000000   

         Geo_France   Geo_Germany     Geo_Spain  
count  10000.000000  10000.000000  10000.000000  
mean       0.501400      0.250900      0.247700  
std        0.500023      0.433553      0.431698  
min        0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000  
50%        1.000000      0.000000      0.000000  
75%        1.000000      1.000000      0.000000  
max        1.000000      1.000000      1.000000

GaussianNB(priors=None, var_smoothing=1e-09)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
xtr, xts, ytr, yts = train_test_split(x,y,test_size = 0.3, random_state = 7)

In [16]:
print(xtr.shape)

(7000, 12)


In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
clf = GaussianNB()

In [24]:
clf.fit(xtr, ytr)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
y_pred = clf.predict(xts)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(yts, y_pred, normalize=True, sample_weight=None)

0.7906666666666666

In [30]:
from sklearn.model_selection import cross_val_score
scores= cross_val_score(clf, x, y, cv=5)
print(scores)

[0.78610695 0.7816092  0.789      0.78389195 0.78389195]


In [34]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200, random_state=0, max_features=2)

In [35]:
from sklearn.model_selection import cross_val_score
scores= cross_val_score(rfc, x, y, cv=5)
print(scores)

[0.86206897 0.87206397 0.862      0.86643322 0.85642821]
